var N = null;var sourcesIndex = {};
sourcesIndex["dbus"] = {"name":"","dirs":[{"name":"arg","files":["array_impl.rs","basic_impl.rs","mod.rs","msgarg.rs","variantstruct_impl.rs"]},{"name":"tree","files":["factory.rs","leaves.rs","methodtype.rs","mod.rs","objectpath.rs","utils.rs"]}],"files":["connection.rs","lib.rs","matchrule.rs","message.rs","prop.rs","signalargs.rs","stdintf.rs","strings.rs","watch.rs"]};
sourcesIndex["libc"] = {"name":"","dirs":[{"name":"unix","dirs":[{"name":"linux_like","dirs":[{"name":"linux","dirs":[{"name":"gnu","dirs":[{"name":"b64","dirs":[{"name":"x86_64","files":["mod.rs","not_x32.rs"]}],"files":["mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["fixed_width_ints.rs","lib.rs","macros.rs"]};
sourcesIndex["libdbus_sys"] = {"name":"","files":["lib.rs"]};
sourcesIndex["notify_rust"] = {"name":"","files":["error.rs","hints.rs","lib.rs","miniver.rs","server.rs","util.rs","xdg.rs"]};
sourcesIndex['backtrace'] = {"name":"","dirs":[{"name":"backtrace","dirs":[],"files":["libunwind.rs","mod.rs"]},{"name":"symbolize","dirs":[],"files":["libbacktrace.rs","mod.rs"]}],"files":["capture.rs","dylib.rs","lib.rs"]};
sourcesIndex['backtrace_sys'] = {"name":"","dirs":[],"files":["lib.rs"]};
sourcesIndex['cfg_if'] = {"name":"","dirs":[],"files":["lib.rs"]};
sourcesIndex['dbus'] = {"name":"","dirs":[{"name":"arg","dirs":[],"files":["array_impl.rs","basic_impl.rs","mod.rs","msgarg.rs","variantstruct_impl.rs"]},{"name":"tree","dirs":[],"files":["factory.rs","leaves.rs","methodtype.rs","mod.rs","objectpath.rs","utils.rs"]}],"files":["connection.rs","lib.rs","message.rs","prop.rs","signalargs.rs","stdintf.rs","strings.rs","watch.rs"]};
sourcesIndex['failure'] = {"name":"","dirs":[{"name":"backtrace","dirs":[],"files":["internal.rs","mod.rs"]},{"name":"error","dirs":[],"files":["error_impl.rs","mod.rs"]}],"files":["as_fail.rs","box_std.rs","compat.rs","context.rs","error_message.rs","lib.rs","macros.rs","result_ext.rs","sync_failure.rs"]};
sourcesIndex['failure_derive'] = {"name":"","dirs":[],"files":["lib.rs"]};
sourcesIndex['libc'] = {"name":"","dirs":[{"name":"unix","dirs":[{"name":"notbsd","dirs":[{"name":"linux","dirs":[{"name":"other","dirs":[{"name":"b64","dirs":[],"files":["mod.rs","not_x32.rs","x86_64.rs"]}],"files":["mod.rs"]}],"files":["mod.rs"]}],"files":["mod.rs"]}],"files":["mod.rs"]}],"files":["dox.rs","lib.rs","macros.rs"]};
sourcesIndex['libdbus_sys'] = {"name":"","dirs":[],"files":["lib.rs"]};
sourcesIndex['notify_rust'] = {"name":"","dirs":[],"files":["error.rs","hints.rs","lib.rs","miniver.rs","server.rs","util.rs","xdg.rs"]};
sourcesIndex['notify_rust'] = {"name":"","dirs":[],"files":["error.rs","hints.rs","lib.rs","miniver.rs","server.rs","util.rs","xdg.rs"]};
sourcesIndex['notify_rust'] = {"name":"","dirs":[],"files":["error.rs","hints.rs","lib.rs","miniver.rs","server.rs","util.rs","xdg.rs"]};
sourcesIndex['notify_rust'] = {"name":"","dirs":[],"files":["error.rs","hints.rs","lib.rs","miniver.rs","server.rs","util.rs","xdg.rs"]};
sourcesIndex['notify_rust'] = {"name":"","dirs":[],"files":["error.rs","hints.rs","lib.rs","miniver.rs","server.rs","util.rs","xdg.rs"]};
sourcesIndex['notify_rust'] = {"name":"","dirs":[],"files":["error.rs","hints.rs","lib.rs","miniver.rs","server.rs","util.rs","xdg.rs"]};
sourcesIndex['proc_macro2'] = {"name":"","dirs":[],"files":["lib.rs","stable.rs","strnom.rs","unstable.rs"]};
sourcesIndex['quote'] = {"name":"","dirs":[],"files":["ext.rs","lib.rs","to_tokens.rs"]};
sourcesIndex['rustc_demangle'] = {"name":"","dirs":[],"files":["lib.rs"]};
sourcesIndex['syn'] = {"name":"","dirs":[{"name":"gen","dirs":[],"files":["gen_helper.rs","visit.rs"]}],"files":["attr.rs","buffer.rs","data.rs","derive.rs","error.rs","export.rs","expr.rs","ext.rs","generics.rs","group.rs","ident.rs","keyword.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","path.rs","print.rs","punctuated.rs","span.rs","spanned.rs","token.rs","tt.rs","ty.rs"]};
sourcesIndex['synstructure'] = {"name":"","dirs":[],"files":["lib.rs","macros.rs"]};
sourcesIndex['unicode_xid'] = {"name":"","dirs":[],"files":["lib.rs","tables.rs"]};
createSourceSidebar();
