(function() {var implementors = {};
implementors["dbus"] = [{text:"impl&lt;'m&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>&gt; for <a class=\"struct\" href=\"dbus/struct.Signature.html\" title=\"struct dbus::Signature\">Signature</a>&lt;'m&gt;",synthetic:false,types:["dbus::strings::Signature"]},{text:"impl&lt;'m&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>&gt; for <a class=\"struct\" href=\"dbus/struct.Path.html\" title=\"struct dbus::Path\">Path</a>&lt;'m&gt;",synthetic:false,types:["dbus::strings::Path"]},{text:"impl&lt;'m&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>&gt; for <a class=\"struct\" href=\"dbus/struct.Member.html\" title=\"struct dbus::Member\">Member</a>&lt;'m&gt;",synthetic:false,types:["dbus::strings::Member"]},{text:"impl&lt;'m&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>&gt; for <a class=\"struct\" href=\"dbus/struct.Interface.html\" title=\"struct dbus::Interface\">Interface</a>&lt;'m&gt;",synthetic:false,types:["dbus::strings::Interface"]},{text:"impl&lt;'m&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>&gt; for <a class=\"struct\" href=\"dbus/struct.BusName.html\" title=\"struct dbus::BusName\">BusName</a>&lt;'m&gt;",synthetic:false,types:["dbus::strings::BusName"]},{text:"impl&lt;'m&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>&gt; for <a class=\"struct\" href=\"dbus/struct.ErrorName.html\" title=\"struct dbus::ErrorName\">ErrorName</a>&lt;'m&gt;",synthetic:false,types:["dbus::strings::ErrorName"]},];
implementors["failure"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;dyn <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> + 'static&gt; for <a class=\"struct\" href=\"failure/struct.Error.html\" title=\"struct failure::Error\">Error</a>",synthetic:false,types:["failure::error::Error"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
