(function() {var implementors = {};
implementors["dbus"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"dbus/struct.MessageItemArray.html\" title=\"struct dbus::MessageItemArray\">MessageItemArray</a>",synthetic:false,types:["dbus::message::MessageItemArray"]},{text:"impl&lt;'m&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"dbus/struct.Signature.html\" title=\"struct dbus::Signature\">Signature</a>&lt;'m&gt;",synthetic:false,types:["dbus::strings::Signature"]},{text:"impl&lt;'m&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"dbus/struct.Path.html\" title=\"struct dbus::Path\">Path</a>&lt;'m&gt;",synthetic:false,types:["dbus::strings::Path"]},{text:"impl&lt;'m&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"dbus/struct.Member.html\" title=\"struct dbus::Member\">Member</a>&lt;'m&gt;",synthetic:false,types:["dbus::strings::Member"]},{text:"impl&lt;'m&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"dbus/struct.Interface.html\" title=\"struct dbus::Interface\">Interface</a>&lt;'m&gt;",synthetic:false,types:["dbus::strings::Interface"]},{text:"impl&lt;'m&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"dbus/struct.BusName.html\" title=\"struct dbus::BusName\">BusName</a>&lt;'m&gt;",synthetic:false,types:["dbus::strings::BusName"]},{text:"impl&lt;'m&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"dbus/struct.ErrorName.html\" title=\"struct dbus::ErrorName\">ErrorName</a>&lt;'m&gt;",synthetic:false,types:["dbus::strings::ErrorName"]},];
implementors["notify_rust"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"notify_rust/struct.NotificationHandle.html\" title=\"struct notify_rust::NotificationHandle\">NotificationHandle</a>",synthetic:false,types:["notify_rust::xdg::NotificationHandle"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"notify_rust/struct.SPEC_VERSION.html\" title=\"struct notify_rust::SPEC_VERSION\">SPEC_VERSION</a>",synthetic:false,types:["notify_rust::SPEC_VERSION"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
